"""Backward-compatible facade for API response models."""

from .batch_responses import (
    BatchJobResultsResponse,
    BatchJobStatusEnum,
    BatchJobStatusResponse,
    BatchJobSubmissionResponse,
    BatchScenarioResultItem,
    BatchScenarioStatus,
    BatchSummaryArtifact,
)
from .common_responses import (
    ConfigReferenceType,
    ConsistencyCheckResponse,
    ErrorCategory,
    ErrorDetails,
    ErrorResponse,
    OutOfScopeReference,
)
from .run_responses import (
    RunArtifact,
    RunArtifactType,
    RunSessionFolderImportResponse,
    RunSessionResponse,
    RunSessionState,
    RunSessionStatusEnum,
    RunSolveResponse,
)
from .solver_responses import (
    ExecutionResponse,
    ExecutionStatus,
    ExecutionStatusEnum,
    HealthResponse,
    SolverExecution,
    SolverResults,
    SolverStatusEnum,
)
from .spreadsheet_responses import (
    ColumnValidationError,
    ExtractedEntities,
    HeaderValidationError,
    SpreadsheetDiscoveryResponse,
    SpreadsheetFileInfo,
    SpreadsheetFileTypeEnum,
    SpreadsheetValidationResponse,
    SpreadsheetValidationResult,
    ValidationErrorCategory,
)

__all__ = [
    "ErrorCategory",
    "ErrorDetails",
    "ErrorResponse",
    "ConfigReferenceType",
    "OutOfScopeReference",
    "ConsistencyCheckResponse",
    "ExecutionStatusEnum",
    "SolverStatusEnum",
    "SolverResults",
    "ExecutionStatus",
    "SolverExecution",
    "ExecutionResponse",
    "HealthResponse",
    "RunSessionStatusEnum",
    "RunSessionState",
    "RunSessionResponse",
    "RunSessionFolderImportResponse",
    "RunSolveResponse",
    "RunArtifactType",
    "RunArtifact",
    "BatchJobStatusEnum",
    "BatchScenarioStatus",
    "BatchJobSubmissionResponse",
    "BatchJobStatusResponse",
    "BatchScenarioResultItem",
    "BatchSummaryArtifact",
    "BatchJobResultsResponse",
    "SpreadsheetFileTypeEnum",
    "SpreadsheetFileInfo",
    "SpreadsheetDiscoveryResponse",
    "ValidationErrorCategory",
    "ColumnValidationError",
    "HeaderValidationError",
    "SpreadsheetValidationResult",
    "ExtractedEntities",
    "SpreadsheetValidationResponse",
]
