"""Domain models for the planner backend."""
from backend.src.domain.spreadsheet.entities import (
    SpreadsheetFileType,
    ValidationErrorCategory,
    SpreadsheetFileInfo,
    HeaderValidationError,
    ColumnValidationError,
    ExtractedEntities,
    SpreadsheetValidationResult,
)
from backend.src.domain.configuration import (
    ConfigReferenceType,
    OutOfScopeReference,
    ConfigConsistencyCheckResult,
    ProjectConfig,
    LegTypeConfig,
    LegConfig,
    TestTypeConfig,
    TestConfig,
    FTEConfig,
    EquipmentConfig,
    EffectiveSettings,
)
from backend.src.domain.scenario import (
    ScenarioQueueStatus,
    QueuedScenario,
    ScenarioQueueStatus as QueueStatus,
    AddScenarioToQueue,
    QueuedScenarioResponse,
    RunScenarioResult,
    RunAllUnsolvedResult,
    StopRenderResult,
    RunArtifact,
    RunArtifactType,
)
from backend.src.domain.entity import (
    EntityIndex,
    ProjectEntity,
    LegTypeEntity,
    LegEntity,
    TestTypeEntity,
    TestEntity,
    FTEEntity,
    EquipmentEntity,
    ExternalReference,
    ValidationWarning,
)

__all__ = [
    # Spreadsheet
    "SpreadsheetFileType",
    "ValidationErrorCategory",
    "SpreadsheetFileInfo",
    "HeaderValidationError",
    "ColumnValidationError",
    "ExtractedEntities",
    "SpreadsheetValidationResult",
    # Configuration
    "ConfigReferenceType",
    "OutOfScopeReference",
    "ConfigConsistencyCheckResult",
    "ProjectConfig",
    "LegTypeConfig",
    "LegConfig",
    "TestTypeConfig",
    "TestConfig",
    "FTEConfig",
    "EquipmentConfig",
    "EffectiveSettings",
    # Scenario
    "ScenarioQueueStatus",
    "QueuedScenario",
    "QueueStatus",
    "AddScenarioToQueue",
    "QueuedScenarioResponse",
    "RunScenarioResult",
    "RunAllUnsolvedResult",
    "StopRenderResult",
    "RunArtifact",
    "RunArtifactType",
    # Entity
    "EntityIndex",
    "ProjectEntity",
    "LegTypeEntity",
    "LegEntity",
    "TestTypeEntity",
    "TestEntity",
    "FTEEntity",
    "EquipmentEntity",
    "ExternalReference",
    "ValidationWarning",
]
